### ISSUE TITLE
Address goerr113 issues

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#102]
When running the code through the `goerr113` linter:
```
golangci-lint run --disable-all -E goerr113
```
We see errors such as:
```
pkg/cdi/qualified-device.go:185:11: err113: do not define dynamic errors, use wrapped static errors instead: "fmt.Errorf(\"invalid character '%c' in device name %q\",\n\tc, name)" (goerr113)
                        return fmt.Errorf("invalid character '%c' in device name %q",
```
Which I take to mean that these errors are not comparable and should rather be instatiated as:

```
errorInvalid := errors.New("invalid")
...
return fmt.Errorf("%w: invalid character '%c' in device name %q", errorInvalid, c, name)
```

We should:
1. Enable this linter on our code base
2. Address these errors

**Comment by pohly** [comment]
I am not sure whether I agree with this linter. When error wrapping was introduced as a language feature, it was explicitly stated that "whether to wrap" is a case-by-case design decision - see that section in https://go.dev/blog/go1.13-errors

If you decide to wrap base errors, those base error would have to be exported. Otherwise wrapping makes no sense because nothing can take advantage of it. So the question becomes: is that a useful API change?
