### ISSUE TITLE
On Windows CDI device injection will fail if device spec is complete

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#131]
On Windows builds the injection of devices will fail even if no additional information is required since [`fillMissingInfo`](https://github.com/container-orchestrated-devices/container-device-interface/blob/fca21545c4761414626d1632888497c211a9f799/pkg/cdi/container-edits_windows.go#L25-L27) is implemented to raise an error.

This will have to be addressed to support device injection for Linux Containers on Windows (LCOW) and is related to #28.

See https://github.com/moby/moby/pull/45134#discussion_r1144132968

**Comment by TBBle** [comment]
Hmm, I think a little bit of context was lost.

The failure is on _Windows_ builds, as the Windows platform-specific implementation of [`fillMissingInfo`](https://github.com/container-orchestrated-devices/container-device-interface/blob/fca21545c4761414626d1632888497c211a9f799/pkg/cdi/container-edits_windows.go#L25-L27) is missing the [early-out part seen in the !Windows implementation](https://github.com/container-orchestrated-devices/container-device-interface/blob/fca21545c4761414626d1632888497c211a9f799/pkg/cdi/container-edits_unix.go#L30-L36).

There's no current practical situation where this matters AFAIK, but fixing this will unblock a potential use-case for CDI with LCOW before #28 is implemented. I haven't checked if hcsshim actually supports Linux devices sent through in the OCI spec for LCOW or not, which is why this is a "potential" use-case. It may be more important once #28 is implemented since host devices for LCOW are exposed to the uvm though the Windows Devices block, but I don't remember if the linux-side device nodes also need to be specified, or are internally generated by hcsshim.

Also, to be clear, if no `DeviceNodes` are provided in the CDI spec, then it won't fail on Windows, as `fillMissingInfo` won't be called. So env-vars, mounts, and hooks would be injected correctly already.
